Repository pi-base/data, pull requests merged in 2024-12, with the labels that each got.

#1065 Suggest a PR for traits rather than issue
  .github/ISSUE_TEMPLATE/new-trait-suggestion.md
Labels: meta, review-requested

#1030 Countably compact + meta-Lindelof => compact
  properties/P000016.md
  theorems/T000107.md
Labels: under-review

#1079 Metacompact cleanup
  spaces/S000035/properties/P000031.md
  spaces/S000052/properties/P000031.md
  spaces/S000056/properties/P000031.md
  spaces/S000066/properties/P000031.md
  spaces/S000067/properties/P000031.md
  spaces/S000071/properties/P000031.md
  spaces/S000072/properties/P000031.md
  spaces/S000073/properties/P000031.md
  spaces/S000080/properties/P000031.md
  spaces/S000098/properties/P000031.md
Labels: under-review

#1087 More instructive first line for S72
  spaces/S000072/README.md
Labels: review-requested

#1088 better first lines for properties with multiple characterizations
  properties/P000090.md
  properties/P000185.md
  properties/P000195.md
  properties/P000196.md
Labels: seeking-reviewer

#1078 Rudin's Dowker space is a P-space and not realcompact
  spaces/S000138/properties/P000147.md
  spaces/S000138/properties/P000162.md
Labels: seeking-reviewer

#1073 Two new theorems about monotonically normal and hereditarily collectionwise normal
  theorems/T000663.md
  theorems/T000664.md
Labels: review-requested

#1082 Weak topology is Hemicompact more than σ-compact
  spaces/S000021/properties/P000017.md
  spaces/S000021/properties/P000111.md
Labels: review-requested

#1095 sequential compact/closed characterization of P99 US
  properties/P000099.md
Labels: review-requested

#989 Adding examples for semimetrizable and symmetrizable
  spaces/S000015/properties/P000002.md
  spaces/S000015/properties/P000027.md
  spaces/S000015/properties/P000037.md
  spaces/S000015/properties/P000099.md
  spaces/S000015/properties/P000102.md
  spaces/S000015/properties/P000129.md
  spaces/S000156/properties/P000079.md
  spaces/S000156/properties/P000104.md
Labels: review-requested

#1099 S30 and S32 not embeddable into Euclidean space
  spaces/S000030/properties/P000184.md
  spaces/S000032/properties/P000184.md
Labels: review-requested

#1102 Double origin plane S66 does not have a cut point P204
  spaces/S000066/README.md
  spaces/S000066/properties/P000204.md
Labels: seeking-reviewer

#1069 Long spaces (S38, S39, S40, S153 S196) cut point properties / removing homogeneous traits / trait cleanup
  spaces/S000038/properties/P000018.md
  spaces/S000038/properties/P000029.md
  spaces/S000038/properties/P000086.md
  spaces/S000038/properties/P000205.md
  spaces/S000039/properties/P000029.md
  spaces/S000039/properties/P000086.md
  spaces/S000039/properties/P000129.md
  spaces/S000040/properties/P000036.md
  spaces/S000040/properties/P000054.md
  spaces/S000040/properties/P000086.md
  spaces/S000040/properties/P000204.md
  spaces/S000040/properties/P000205.md
  spaces/S000153/properties/P000038.md
Labels: seeking-reviewer

#1097 Part 1 of #1018: A new theorem about spectral spaces and adding traits for S45
  spaces/S000045/properties/P000001.md
  spaces/S000045/properties/P000073.md
  spaces/S000045/properties/P000075.md
  spaces/S000045/properties/P000208.md
  theorems/T000675.md
Labels: review-requested

#1107 Clearing up traits for S9 and adding it is neither P194 nor P205
  spaces/S000009/properties/P000001.md
  spaces/S000009/properties/P000002.md
  spaces/S000009/properties/P000026.md
  spaces/S000009/properties/P000033.md
  spaces/S000009/properties/P000037.md
  spaces/S000009/properties/P000038.md
  spaces/S000009/properties/P000039.md
  spaces/S000009/properties/P000040.md
  spaces/S000009/properties/P000043.md
  spaces/S000009/properties/P000051.md
  spaces/S000009/properties/P000194.md
  spaces/S000009/properties/P000201.md
  spaces/S000009/properties/P000205.md
Labels: cleanup, seeking-reviewer

#1108 Countable box product of reals is not totally path disconnected
  spaces/S000107/properties/P000046.md
Labels: seeking-reviewer

#1113 Cleaning up the traits for S13
  spaces/S000013/properties/P000001.md
  spaces/S000013/properties/P000002.md
  spaces/S000013/properties/P000014.md
  spaces/S000013/properties/P000016.md
  spaces/S000013/properties/P000034.md
  spaces/S000013/properties/P000038.md
  spaces/S000013/properties/P000039.md
  spaces/S000013/properties/P000045.md
  spaces/S000013/properties/P000051.md
  spaces/S000013/properties/P000054.md
  spaces/S000013/properties/P000126.md
  spaces/S000013/properties/P000202.md
  spaces/S000013/properties/P000203.md
Labels: cleanup, seeking-reviewer

#1110 Cleaning up the traits for S12
  spaces/S000012/properties/P000001.md
  spaces/S000012/properties/P000002.md
  spaces/S000012/properties/P000014.md
  spaces/S000012/properties/P000016.md
  spaces/S000012/properties/P000027.md
  spaces/S000012/properties/P000034.md
  spaces/S000012/properties/P000039.md
  spaces/S000012/properties/P000045.md
  spaces/S000012/properties/P000051.md
  spaces/S000012/properties/P000057.md
  spaces/S000012/properties/P000126.md
  spaces/S000012/properties/P000181.md
  spaces/S000012/properties/P000202.md
  spaces/S000012/properties/P000203.md
Labels: cleanup, seeking-reviewer

#1114 Long circle has no cut point
  spaces/S000196/properties/P000204.md
Labels: under-review

#1112 New theorem: has a focal point plus a local property implies the global property
  theorems/T000676.md
Labels: seeking-reviewer

#1115 Strengthening T451 to Indiscrete + Cardinality $\geq c$ => Locally arc connected
  theorems/T000451.md
Labels: review-requested

#1103 Part 5 of #1018: Adding two new hereditarily connected spectral spaces
  spaces/S000166/README.md
  spaces/S000166/properties/P000073.md
  spaces/S000166/properties/P000090.md
  spaces/S000166/properties/P000181.md
  spaces/S000166/properties/P000196.md
  spaces/S000166/properties/P000202.md
  spaces/S000166/properties/P000208.md
  spaces/S000167/README.md
  spaces/S000167/properties/P000051.md
  spaces/S000167/properties/P000073.md
  spaces/S000167/properties/P000090.md
  spaces/S000167/properties/P000139.md
  spaces/S000167/properties/P000181.md
  spaces/S000167/properties/P000196.md
  spaces/S000167/properties/P000202.md
  spaces/S000167/properties/P000208.md
Labels: seeking-reviewer

#1111 Almost discrete spaces are hereditarily collectionwise normal
  theorems/T000575.md
Labels: review-requested

#1109 Adding two new theorems: "Almost discrete => Sober" and "Almost discrete + Compact => Spectral"
  theorems/T000605.md
  theorems/T000606.md
Labels: review-requested

#1117 Tweak to T589 (indiscrete => simply connected)
  theorems/T000589.md
Labels: review-requested

#1124 Adding missing traits to cofinite topology on $\omega$
  spaces/S000015/properties/P000138.md
  spaces/S000015/properties/P000142.md
Labels: seeking-reviewer

#1125 Add non-game theoretic traits to cofinite topology on $\mathbb{R}$
  spaces/S000016/properties/P000101.md
  spaces/S000016/properties/P000142.md
  spaces/S000016/properties/P000199.md
Labels: seeking-reviewer

#1126 Cofinite and cocountable topology on $\mathbb{R}$ is strongly Choquet
  spaces/S000016/properties/P000206.md
  spaces/S000017/properties/P000206.md
Labels: seeking-reviewer

#1120 Add missing traits to particular point topology on $\omega$
  spaces/S000008/properties/P000194.md
  spaces/S000008/properties/P000205.md
Labels: under-review

#1131 Traits cleanup for S8
  spaces/S000008/properties/P000001.md
  spaces/S000008/properties/P000002.md
  spaces/S000008/properties/P000027.md
  spaces/S000008/properties/P000033.md
  spaces/S000008/properties/P000037.md
  spaces/S000008/properties/P000038.md
  spaces/S000008/properties/P000039.md
  spaces/S000008/properties/P000040.md
  spaces/S000008/properties/P000051.md
  spaces/S000008/properties/P000057.md
  spaces/S000008/properties/P000181.md
  spaces/S000008/properties/P000201.md
Labels: seeking-reviewer

#1098 Part 2 of #1018: An example of a space that is hyperconnected, ultraconnected, compact, sober, and Alexandrov, but not spectral
  spaces/S000152/README.md
  spaces/S000152/properties/P000039.md
  spaces/S000152/properties/P000073.md
  spaces/S000152/properties/P000075.md
  spaces/S000152/properties/P000090.md
  spaces/S000152/properties/P000181.md
  spaces/S000152/properties/P000202.md
Labels: under-review

#1132 Add some traits for cocountable topology on $\mathbb{R}$
  spaces/S000017/README.md
  spaces/S000017/properties/P000071.md
  spaces/S000017/properties/P000126.md
  spaces/S000017/properties/P000172.md
  spaces/S000017/properties/P000189.md
Labels: seeking-reviewer

#1119 Partition topology implies strongly Choquet
  theorems/T000680.md
Labels: review-requested

#1133 Completing S48, the cofinite topology on $\omega$ extended by a non-open generic point
  spaces/S000048/properties/P000001.md
  spaces/S000048/properties/P000013.md
  spaces/S000048/properties/P000027.md
  spaces/S000048/properties/P000042.md
  spaces/S000048/properties/P000044.md
  spaces/S000048/properties/P000051.md
  spaces/S000048/properties/P000056.md
  spaces/S000048/properties/P000057.md
  spaces/S000048/properties/P000089.md
  spaces/S000048/properties/P000129.md
  spaces/S000048/properties/P000138.md
  spaces/S000048/properties/P000181.md
  spaces/S000048/properties/P000192.md
Labels: seeking-reviewer

#1136 Minor cleanup of door traits
  spaces/S000014/properties/P000126.md
  spaces/S000188/properties/P000126.md
  theorems/T000447.md
Labels: seeking-reviewer

#1134 T681: Ultraparacompact spaces are fully normal
  theorems/T000575.md
  theorems/T000681.md
Labels: review-requested

#1138 Definition of realcompactness
  properties/P000162.md
Labels: under-review

#1142 Fix description of S142 (Erdos space)
  spaces/S000142/README.md
Labels: review-requested

#1137 T682: Noetherian spaces with generic point have fixed point property
  spaces/S000007/properties/P000089.md
  spaces/S000010/properties/P000089.md
  spaces/S000048/properties/P000001.md
  spaces/S000048/properties/P000089.md
  spaces/S000144/properties/P000089.md
  spaces/S000187/properties/P000089.md
  theorems/T000682.md
Labels: review-requested

#1145 Everywhere doubled line is not hereditarily separable
  spaces/S000086/properties/P000198.md
Labels: under-review

#1105 Adding a new space: Rationals extended by a focal point, as an example of a weakly locally compact semiregular space that is not Baire
  spaces/S000050/README.md
  spaces/S000050/properties/P000010.md
  spaces/S000050/properties/P000014.md
  spaces/S000050/properties/P000027.md
  spaces/S000050/properties/P000041.md
  spaces/S000050/properties/P000045.md
  spaces/S000050/properties/P000056.md
  spaces/S000050/properties/P000130.md
  spaces/S000050/properties/P000181.md
  spaces/S000050/properties/P000192.md
  spaces/S000050/properties/P000202.md
Labels: review-requested

#1147 Add T683: Almost discrete symmetrizable spaces are semimetrizable
  theorems/T000683.md
Labels: under-review

#1100 Part 3 of #1018: Right open-ray topology on $[0,1]$
  spaces/S000158/README.md
  spaces/S000159/README.md
  spaces/S000159/properties/P000027.md
  spaces/S000159/properties/P000043.md
  spaces/S000159/properties/P000073.md
  spaces/S000159/properties/P000075.md
  spaces/S000159/properties/P000130.md
  spaces/S000159/properties/P000139.md
  spaces/S000159/properties/P000196.md
  spaces/S000159/properties/P000202.md
Labels: under-review

#1146 Strengthening T622 to Ultraconnected + Shrinking + not Empty => Has a focal point
  theorems/T000622.md
Labels: under-review

#1101 Part 4 of #1018: Right open-ray topology on $\omega+1$
  spaces/S000160/README.md
  spaces/S000160/properties/P000073.md
  spaces/S000160/properties/P000139.md
  spaces/S000160/properties/P000181.md
  spaces/S000160/properties/P000196.md
  spaces/S000160/properties/P000208.md
Labels: under-review

#1143 Metrizable + realcompact => non-measurable cardinality, and improved definition of non-measurable cardinality
  properties/P000164.md
  spaces/S000136/properties/P000164.md
  spaces/S000138/properties/P000164.md
  spaces/S001103/properties/P000164.md
  theorems/T000394.md
Labels: under-review

#1128 Part 1 of completing S110
  spaces/S000110/properties/P000018.md
  spaces/S000110/properties/P000021.md
  spaces/S000110/properties/P000028.md
  spaces/S000110/properties/P000059.md
  spaces/S000110/properties/P000093.md
  spaces/S000110/properties/P000132.md
  spaces/S000110/properties/P000147.md
  spaces/S000110/properties/P000198.md
Labels: seeking-reviewer

#1148 Pointed rational extension of R has uncountable extent
  spaces/S000060/README.md
  spaces/S000060/properties/P000018.md
  spaces/S000060/properties/P000027.md
  spaces/S000060/properties/P000093.md
  spaces/S000060/properties/P000198.md
Labels: under-review

#1129 Part 2 of completing S110
  spaces/S000110/properties/P000103.md
  spaces/S000110/properties/P000136.md
Labels: review-requested

#1130 Part 3 of completing S110
  spaces/S000110/properties/P000117.md
  spaces/S000110/properties/P000206.md
Labels: review-requested

#1140 Niemytzki plane is semimetrizable
  spaces/S000074/properties/P000102.md
Labels: under-review

#1154 Fix/tweak S122 description
  spaces/S000122/README.md
Labels: under-review

#1162 Adding P102 (Semimetrizable) to S60 (Pointed rational extension of reals) and S61 (Pointed irrational extension of reals)
  spaces/S000060/properties/P000102.md
  spaces/S000061/properties/P000102.md
Labels: seeking-reviewer

#1159 Introduce S209 Circle with two origins
  spaces/S000209/README.md
  spaces/S000209/properties/P000016.md
  spaces/S000209/properties/P000038.md
  spaces/S000209/properties/P000101.md
  spaces/S000209/properties/P000123.md
  spaces/S000209/properties/P000169.md
  spaces/S000209/properties/P000200.md
  spaces/S000209/properties/P000204.md
Labels: under-review

#1161 Strengthening T683 to Almost discrete + Sequential => Fréchet Urysohn and Fixing T627 and T628
  spaces/S000016/properties/P000104.md
  theorems/T000627.md
  theorems/T000628.md
  theorems/T000683.md
Labels: review-requested

#881 Add aliases to S139 and S201
  spaces/S000139/README.md
  spaces/S000201/README.md
Labels: under-review

#1135 Rudin's Dowker space is not $T_5$
  spaces/S000138/properties/P000008.md
Labels: under-review

#1156 Semimetrizability of multi-pointed lines
  spaces/S000065/properties/P000102.md
  spaces/S000065/properties/P000122.md
  spaces/S000083/properties/P000102.md
  spaces/S000084/properties/P000102.md
  spaces/S000085/properties/P000102.md
  spaces/S000086/properties/P000104.md
Labels: under-review

#1169 Restore trait P36 Connected to S188
  spaces/S000188/properties/P000036.md
Labels: review-requested

#1168 Strengthen T513, as shown in #1167
  spaces/S000008/properties/P000192.md
  spaces/S000009/properties/P000192.md
  spaces/S000047/properties/P000073.md
  spaces/S000199/properties/P000192.md
  theorems/T000513.md
Labels: under-review

#1144 Add Q^ω, as a better distinguishment of Erdős space
  spaces/S000030/properties/P000066.md
  spaces/S000142/README.md
  spaces/S000146/README.md
  spaces/S000146/properties/P000027.md
  spaces/S000146/properties/P000050.md
  spaces/S000146/properties/P000053.md
  spaces/S000146/properties/P000056.md
  spaces/S000146/properties/P000065.md
  spaces/S000146/properties/P000066.md
  spaces/S000146/properties/P000087.md
Labels: awaiting-author

#1104 show long circle is T5 but not perfectly normal
  properties/P000015.md
  properties/P000067.md
  properties/P000081.md
  spaces/S000196/properties/P000003.md
  spaces/S000196/properties/P000008.md
  spaces/S000196/properties/P000081.md
Labels: under-review
