Repository pi-base/data, pull requests merged in 2025-01, with the labels that each got.

#1178 Almost discrete - door cleanup
  spaces/S000010/properties/P000126.md
  spaces/S000010/properties/P000203.md
  spaces/S000011/properties/P000126.md
  spaces/S000011/properties/P000203.md
  spaces/S000020/properties/P000126.md
  spaces/S000020/properties/P000203.md
  spaces/S000022/properties/P000126.md
  spaces/S000022/properties/P000203.md
  spaces/S000023/properties/P000126.md
  spaces/S000023/properties/P000203.md
  spaces/S000033/properties/P000126.md
  spaces/S000033/properties/P000203.md
  spaces/S000034/properties/P000126.md
  spaces/S000111/properties/P000126.md
  spaces/S000111/properties/P000203.md
  spaces/S000131/properties/P000126.md
  spaces/S000131/properties/P000203.md
  spaces/S000133/properties/P000126.md
  spaces/S000133/properties/P000203.md
  spaces/S000154/properties/P000126.md
  spaces/S000154/properties/P000203.md
  spaces/S000202/properties/P000126.md
  spaces/S000202/properties/P000203.md
Labels: review-requested

#1177 Combine P57 P78 traits into P181 countably infinite
  spaces/S000020/properties/P000057.md
  spaces/S000020/properties/P000078.md
  spaces/S000020/properties/P000181.md
  spaces/S000034/properties/P000057.md
  spaces/S000034/properties/P000078.md
  spaces/S000034/properties/P000181.md
  spaces/S000161/properties/P000057.md
  spaces/S000161/properties/P000078.md
  spaces/S000161/properties/P000181.md
Labels: review-requested

#1167 Add S51 Khalimsky line, an example of a non-T1 cut point space
  properties/P000193.md
  spaces/S000051/README.md
  spaces/S000051/properties/P000010.md
  spaces/S000051/properties/P000021.md
  spaces/S000051/properties/P000024.md
  spaces/S000051/properties/P000089.md
  spaces/S000051/properties/P000094.md
  spaces/S000051/properties/P000145.md
  spaces/S000051/properties/P000181.md
  spaces/S000051/properties/P000205.md
Labels: under-review

#1170 S60: homogeneity, cut points and more
  spaces/S000060/properties/P000028.md
  spaces/S000060/properties/P000036.md
  spaces/S000060/properties/P000046.md
  spaces/S000060/properties/P000056.md
  spaces/S000060/properties/P000082.md
  spaces/S000060/properties/P000086.md
  spaces/S000060/properties/P000089.md
  spaces/S000060/properties/P000132.md
  spaces/S000060/properties/P000189.md
  spaces/S000060/properties/P000205.md
Labels: under-review

#1180 Noetherian spaces with a countable k-network are second countable.
  spaces/S000016/properties/P000183.md
  theorems/T000687.md
Labels: under-review

#1182 Irrational slope topology (cut point, local metrizability, and more)
  spaces/S000067/README.md
  spaces/S000067/properties/P000022.md
  spaces/S000067/properties/P000027.md
  spaces/S000067/properties/P000044.md
  spaces/S000067/properties/P000082.md
  spaces/S000067/properties/P000086.md
  spaces/S000067/properties/P000089.md
  spaces/S000067/properties/P000102.md
  spaces/S000067/properties/P000129.md
  spaces/S000067/properties/P000138.md
  spaces/S000067/properties/P000204.md
Labels: under-review

#1186 Cleanup traits of S145 (Free ultrafilter topology on ω)
  spaces/S000145/properties/P000044.md
  spaces/S000145/properties/P000086.md
  spaces/S000145/properties/P000089.md
  spaces/S000145/properties/P000101.md
  spaces/S000145/properties/P000138.md
Labels: under-review

#1173 Tweaks for S139 S201
  spaces/S000139/README.md
  spaces/S000201/README.md
Labels: review-requested

#1092 Fix S72 description
  spaces/S000072/README.md
Labels: review-requested

#1190 Missing traits for Wheel without its hub
  spaces/S000129/properties/P000023.md
  spaces/S000129/properties/P000038.md
  spaces/S000129/properties/P000043.md
  spaces/S000129/properties/P000053.md
  spaces/S000129/properties/P000055.md
  spaces/S000129/properties/P000065.md
  spaces/S000129/properties/P000068.md
  spaces/S000129/properties/P000086.md
  spaces/S000129/properties/P000089.md
  spaces/S000129/properties/P000129.md
  spaces/S000129/properties/P000166.md
  spaces/S000129/properties/P000198.md
  spaces/S000129/properties/P000200.md
  spaces/S000129/properties/P000205.md
Labels: under-review

#1197 meta-properties with Kolmogorov quotient
  properties/P000002.md
  properties/P000003.md
  properties/P000005.md
  properties/P000006.md
  properties/P000011.md
  properties/P000012.md
  properties/P000013.md
  properties/P000018.md
  properties/P000053.md
  properties/P000073.md
  properties/P000082.md
  properties/P000121.md
  properties/P000134.md
  properties/P000135.md
  properties/P000144.md
  properties/P000145.md
  properties/P000192.md
  theorems/T000030.md
Labels: seeking-reviewer

#1196 Misra's subspace of E_0 is totally separated
  spaces/S000178/properties/P000048.md
Labels: under-review

#1195 Extremally disconnected P-space => discrete
  spaces/S000022/properties/P000049.md
  theorems/T000691.md
Labels: under-review

#1192 Update S132 (Duncan's space)
  spaces/S000132/README.md
  spaces/S000132/properties/P000017.md
  spaces/S000132/properties/P000023.md
  spaces/S000132/properties/P000026.md
  spaces/S000132/properties/P000048.md
  spaces/S000132/properties/P000053.md
  spaces/S000132/properties/P000056.md
  spaces/S000132/properties/P000058.md
  spaces/S000132/properties/P000065.md
  spaces/S000132/properties/P000066.md
  spaces/S000132/properties/P000129.md
  spaces/S000132/properties/P000184.md
Labels: seeking-reviewer

#1191 Some missing traits for Radial intervals at 0 (S135)
  spaces/S000135/README.md
  spaces/S000135/properties/P000018.md
  spaces/S000135/properties/P000023.md
  spaces/S000135/properties/P000026.md
  spaces/S000135/properties/P000028.md
  spaces/S000135/properties/P000029.md
  spaces/S000135/properties/P000030.md
  spaces/S000135/properties/P000034.md
  spaces/S000135/properties/P000038.md
  spaces/S000135/properties/P000043.md
  spaces/S000135/properties/P000056.md
  spaces/S000135/properties/P000065.md
  spaces/S000135/properties/P000080.md
  spaces/S000135/properties/P000086.md
  spaces/S000135/properties/P000089.md
  spaces/S000135/properties/P000129.md
  spaces/S000135/properties/P000132.md
  spaces/S000135/properties/P000166.md
  spaces/S000135/properties/P000187.md
  spaces/S000135/properties/P000198.md
  spaces/S000135/properties/P000199.md
  spaces/S000135/properties/P000205.md
  spaces/S000135/properties/P000206.md
Labels: under-review

#1199 Adding theorem on connected strongly paracompact spaces
  theorems/T000692.md
Labels: seeking-reviewer

#1206 P85: Basically disconnected
  properties/P000049.md
  properties/P000085.md
  theorems/T000673.md
  theorems/T000693.md
  theorems/T000694.md
  theorems/T000695.md
  theorems/T000696.md
  theorems/T000697.md
Labels: under-review

#1211 Strengthen T388 and fix wrong trait for S60
  spaces/S000060/properties/P000033.md
  spaces/S000074/properties/P000033.md
  theorems/T000388.md
Labels: under-review

#1207 Cleanup for S22 Fortissimo space on the reals
  spaces/S000022/README.md
  spaces/S000022/properties/P000002.md
  spaces/S000022/properties/P000022.md
  spaces/S000022/properties/P000028.md
  spaces/S000022/properties/P000050.md
  spaces/S000022/properties/P000132.md
Labels: seeking-reviewer

#1215 paracompact + locally compact + connected implies exhaustible by compacts
  theorems/T000698.md
Labels: review-requested

#1176 Circle with two origins fresh
  spaces/S000209/README.md
  spaces/S000209/properties/P000016.md
Labels: under-review

#1220 Semimetrizable spaces are Gδ, add explicit proof to S61|P33
  spaces/S000060/properties/P000132.md
  spaces/S000061/properties/P000033.md
  spaces/S000061/properties/P000102.md
  spaces/S000062/README.md
  spaces/S000063/README.md
  spaces/S000074/properties/P000132.md
  spaces/S000084/properties/P000031.md
  spaces/S000085/properties/P000033.md
  theorems/T000699.md
Labels: under-review
