Repository pi-base/data, pull requests merged in 2025-02, with the labels that each got.

#1224 Trait cleanup related to T698
  spaces/S000129/properties/P000023.md
  spaces/S000134/properties/P000023.md
Labels: review-requested

#1228 Some updates on Everywhere doubled line
  spaces/S000086/properties/P000018.md
  spaces/S000086/properties/P000099.md
  spaces/S000086/properties/P000117.md
  spaces/S000086/properties/P000200.md
  spaces/S000086/properties/P000205.md
Labels: under-review

#1238 A connectedness cleanup
  spaces/S000062/properties/P000036.md
  spaces/S000063/properties/P000036.md
  spaces/S000098/properties/P000036.md
  spaces/S000103/properties/P000036.md
  spaces/S000113/properties/P000036.md
  spaces/S000117/properties/P000036.md
  spaces/S000123/properties/P000036.md
  spaces/S000123/properties/P000045.md
  spaces/S000125/README.md
  spaces/S000125/properties/P000036.md
  spaces/S000125/properties/P000045.md
  spaces/S000164/properties/P000036.md
  spaces/S000188/properties/P000036.md
  spaces/S000198/properties/P000036.md
Labels: seeking-reviewer

#1241 Some remaining traits for S119
  spaces/S000119/README.md
  spaces/S000119/properties/P000036.md
  spaces/S000119/properties/P000037.md
  spaces/S000119/properties/P000046.md
  spaces/S000119/properties/P000089.md
  spaces/S000119/properties/P000129.md
  spaces/S000119/properties/P000189.md
  spaces/S000119/properties/P000204.md
  spaces/S000119/properties/P000205.md
Labels: seeking-reviewer

#1244 Update to Infinite cage S120
  properties/P000055.md
  spaces/S000120/README.md
  spaces/S000120/properties/P000017.md
  spaces/S000120/properties/P000022.md
  spaces/S000120/properties/P000023.md
  spaces/S000120/properties/P000024.md
  spaces/S000120/properties/P000036.md
  spaces/S000120/properties/P000037.md
  spaces/S000120/properties/P000041.md
  spaces/S000120/properties/P000044.md
  spaces/S000120/properties/P000046.md
  spaces/S000120/properties/P000089.md
  spaces/S000120/properties/P000129.md
  spaces/S000120/properties/P000189.md
  spaces/S000120/properties/P000204.md
  spaces/S000120/properties/P000205.md
  spaces/S000120/properties/P000206.md
Labels: trait, cleanup, under-review

#1250 Update to discrete irrational extension
  properties/P000063.md
  spaces/S000063/README.md
  spaces/S000063/properties/P000008.md
  spaces/S000063/properties/P000015.md
  spaces/S000063/properties/P000022.md
  spaces/S000063/properties/P000023.md
  spaces/S000063/properties/P000030.md
  spaces/S000063/properties/P000041.md
  spaces/S000063/properties/P000051.md
  spaces/S000063/properties/P000056.md
  spaces/S000063/properties/P000061.md
  spaces/S000063/properties/P000063.md
  spaces/S000063/properties/P000068.md
  spaces/S000063/properties/P000093.md
  spaces/S000063/properties/P000146.md
  spaces/S000063/properties/P000154.md
  spaces/S000063/properties/P000198.md
  spaces/S000063/properties/P000206.md
Labels: seeking-reviewer
