Repository pi-base/data, pull requests merged in 2025-05, with the labels that each got.

#1293 Fortissimo space of size $\aleph_1$ is 2-Markov Menger
  spaces/S000155/properties/P000072.md
Labels: under-review

#1166 Add some traits for S18 Double pointed cocountable topology on R
  properties/P000001.md
  properties/P000036.md
  properties/P000071.md
  properties/P000147.md
  properties/P000189.md
  properties/P000206.md
  spaces/S000017/properties/P000071.md
  spaces/S000018/README.md
  spaces/S000018/properties/P000001.md
  spaces/S000018/properties/P000013.md
  spaces/S000018/properties/P000028.md
  spaces/S000018/properties/P000039.md
  spaces/S000018/properties/P000071.md
  spaces/S000018/properties/P000139.md
  spaces/S000018/properties/P000147.md
  spaces/S000018/properties/P000189.md
  spaces/S000018/properties/P000206.md
Labels: seeking-reviewer

#1294 Equivalence between Markov Menger and Markov k-Menger for anticompact spaces
  theorems/T000726.md
  theorems/T000727.md
Labels: review-requested
